theme:
  activeBorderColor:
    - "#8aadf4"
    - bold
  inactiveBorderColor:
    - "#a5adcb"
  optionsTextColor:
    - "#8aadf4"
  selectedLineBgColor:
    - "#363a4f"
  selectedRangeBgColor:
    - "#363a4f"
  cherryPickedCommitBgColor:
    - "#494d64"
  cherryPickedCommitFgColor:
    - "#8aadf4"
  unstagedChangesColor:
    - "#ed8796"
  defaultFgColor:
    - "#cad3f5"
  searchingActiveBorderColor:
    - "#eed49f"

keybinding:
  universal:
    prevItem-alt: "j" # go one line up
    nextItem-alt: "k" # go one line down
    scrollUpMain-alt1: "J" # main panel scroll up
    scrollDownMain-alt1: "K" # main panel scroll down
  commits:
    moveDownCommit: "<c-k>" # move commit down one
    moveUpCommit: "<c-j>" # move commit up one
