-- return {
-- 	"jackMort/ChatGPT.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("chatgpt").setup({
-- 			api_key_cmd = "secret-tool lookup openai neovim",
-- 			model = "gpt-3.5-turbo",
-- 		})
-- 	end,
-- 	dependencies = {
-- 		"MunifTanjim/nui.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"nvim-telescope/telescope.nvim",
-- 	},
-- }
